### PR TITLE
Fix depreciation warning for Landsat Co1 to Co2 migration in two split commits

### PR DESCRIPTION
**Pull request by thekester**
Fix issue #517

Modification for SDS_download.py:

    `retrieve_images` and `check_images_available` functions: Removed references to Collection 1. Added a comment explaining the deprecation warning.
    Updated to use only Collection 2 for Landsat images.

Modification for SDS_preprocess.py:

    `preprocess_single `function: Removed references to Collection 1. Added a comment explaining the deprecation warning.
    Updated to ensure images are processed using Collection 2 only.

### CODE REVIEW

**Comment by thekester** [comment]
As said on https://github.com/kvos/CoastSat/pull/524 I take care of separating the commit and removed minor formatting issues  so you can focus on the significant changes.

**Comment by kvos** [comment]
I've suggested to remove the `inputs['landsat_collection']` parameter alltogether as it is now not needed since there isn't any collection to choose from. So it simplifies the code to remove it.

**Comment by thekester** [comment]
Yes, I understand. It's just that I think we should keep that parameter for when they release C03, but since there is only C02 for now, I understand that we can remove this parameter.

**Comment by kvos** [comment]
> I've suggested to rem

true, when a new collection comes through we can assess the changes and edit things (I also find the way the collection parameter was passed through the functions was very repetitive, there's probably a more elegant way to do it)

**Comment by kvos** [comment]
thanks for the PR, I will merge.

**Pull request merged**
