### PR TITLE
Fix depreciation warning for Landsat Co1 to Co2 migration

### PR DESCRIPTION
**Pull request by thekester**
Fix issue #517

Modification for SDS_download.py:

    `retrieve_images` and `check_images_available` functions: Removed references to Collection 1. Added a comment explaining the deprecation warning.
    Updated to use only Collection 2 for Landsat images.

Modification for SDS_preprocess.py:

    `preprocess_single `function: Removed references to Collection 1. Added a comment explaining the deprecation warning.
    Updated to ensure images are processed using Collection 2 only.

### CODE REVIEW

**Comment by kvos** [comment]
hi @thekester , thanks for the PR. 
I'm finding it hard to review the commit as everything is highlighted due to code standardisation, can you pls separate into 2 commits so that I can focus on the changes rather than all the small things like spaces and commas? thanks

**Comment by thekester** [comment]
No problem at all. I'll take care of separating the commits today so you can focus on the significant changes without being distracted by minor formatting issues. I'll also create a new PR to solve the conflicts first and then split into 2 commits one for  SDS_download.py and the other one for SDS_preprocess.py

**Comment by kvos** [comment]
thanks a lot!

**Comment by thekester** [comment]
https://github.com/kvos/CoastSat/pull/526

**Pull request closed without merging**
